name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
  pull_request:

env:
  FORCE_COLOR: 1

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.22.10
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    name: Ember Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.22.10
      - run: yarn install --frozen-lockfile
      - run: yarn test:ember

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.20
          - ember-lts-3.26
          - ember-release
        experimental: [false]
        # include:
          # - ember-try-scenario: ember-beta
            # experimental: true
          # - ember-try-scenario: ember-canary
            # experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.22.5

      - run: yarn install --frozen-lockfile

      - name: test
        run: yarn ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup

